language: node_js
node_js:
  - "11"
addons:
  chrome: stable
before_script:
- npm run lint
script:
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
after_success:
- frauci-update-version && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME: Brightspacehypermediacomponents
  - REPO_NAME: enrollments
  - DEFAULT_INCREMENT: patch
  - SAUCE_USERNAME: Desire2Learn
  - secure: H9d3L6VHVMS/Bq61zmRX94KywSSU50bu2TZvPcyuTrPT7hwxGBscHo5vh/q9luOKa7OqtBBKHv5w0GGluEfZnM0QGa9PMUzxkYinS9FOygDHNiN7q4fHWF5WWoswWzwpyaLx+LhHta9iLw5in7p7o+k58itBEyXcehNWwmlGFS84jjI175O0qzeky5aTvxHm+CavGf7Ssn+sT0zoxhLJNGGhM8o24zpFVOdgj3ZZ5vPwiT6yj9WeNROBPkcI8AKTkVrmIj7Ak225siS/MFQ9D/1BYN4CS3XARbbgu92RsCkqp52BT637/gIDupXV/227bhJboKf6Oz9Q839gpwH5ZWIJFtmsR3RfbBBBn6rstrLzm5lzulXTuNMx6TutEOdq+vJbSBT4+jO1UJPJlXu2/GD99yGO5HBMZfcnLVZrbPARR0n6iZqsEfVUp6SOyzOdOB5ByiQ8vyYQwhNLz26YLrOD1QOrqDYC457eTiBqQym/8sMdJYLXcRWyQTEqEF7H19OL6rnEWTi8WOTyF4cT0FgbnNkoR81z7yEaPqGKXes769hmJauuJuHVYvnvi5cpBH52kcIaVNn4jJeEIA/+d2J5vZOluC1cX18E82Al6RQ/OCKiuBgJ/7qahHBsqo10oxB7QQoIZSTZS6cGqiJY8XCiRVbQ8Gtk5d1TtmQpJes=
  - secure: HbYvbDkcEIHeGDJZcScGeBBjfLcp7LCDfP57voSLaWBQaY0W6fpbf/7wcDOBypRee5T1+BS2aR58avuYEnpEP1YlhrPW4sUDans94IYfpL1BRTDLmB8rmIMcidRCkFu5Fa10j5Bib0QJ+s5xSt3wAFt7gTBkcnZa6OGr3FCwCQR4ixvvvDQpr2mMC12SxAzjt7LEj1vrG1oHN137VXpt5XVxTnEj/uIphr+OqgDRe8staSpTsMhlbIJkUt2pYNR3TM8/hSrinW2zy1nEvrzsC475jfuL4meNInGwnY8XfW0ZtFhSJeHnE3oofPvUPhpZxx1vqBQ+i78lqiPHApyZ26Acte0SQW06jiNp+llwbFX4w/GAU7egBbEjfMTjdQCnjnSq3X7m1ODKE7HWdO/wLx45UZt/IIhKJWeKBIwtkCBHsRZjKyf6OugwhYiIsilfKWy+Gr3ADOgVlcRIWThPeKHUtRPXc6/a80eKokXPqQYamzvAlwNLFRSR/Dd5GRKCrHt2M2Om56OvGsgdsUglf3ouLmitUl2epwvPNfRWU82OQ/2n3EmzkLuv///uv/5cI380ay/kzVLHQj2sl4t1zkYS3RC+Dhy/4KvlkBDl+eTBmOjAfho2e1wEzeWKm4xXsIVeW9MaP1JG+imhpJay3NHzHQM6umEC21xLiBphlHg=
